spring:
  data:
    rest:
      defaultMediaType: application/json

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.200.100.63/product_catalog
    username: user
    password: user
    testOnBorrow: true
    validationQuery: SELECT 1

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5Dialect'
    hibernate:
      ddl-auto: 'update'